[package]
name = "hgrep"
version = "0.1.5"
edition = "2018"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = """
hgrep is a grep tool with human-friendly search output. It eats results of
`grep -nH` and prints the matched position with code snippets.

This is similar to `-C` option of `grep` command, but its output is enhanced
with syntax highlighting. It focuses on human readable outputs. hgrep is useful
to survey the matches with contexts around them. When some matches are near
enough, hgrep prints the lines within one code snippet. To show contexts
efficiently, hgrep adopt some heuristics around empty lines.

hgrep provides a builtin subset implementation of ripgrep as optional feature.
"""
license = "MIT"
homepage = "https://github.com/rhysd/hgrep#readme"
repository = "https://github.com/rhysd/hgrep"
readme = "README.md"
include = [
    "/assets/bat/assets/themes.bin",
    "/assets/bat/assets/syntaxes.bin",
    "/src",
    "/LICENSE.txt",
    "/README.md",
]
categories = ["command-line-utilities", "text-processing"]
keywords = ["grep", "search", "syntax-highlighting", "ripgrep", "bat"]

[[bin]]
name = "hgrep"
path = "src/main.rs"

[features]
default = ["ripgrep", "bat-printer", "syntect-printer"]
ripgrep = [
    "grep-matcher",
    "grep-pcre2",
    "grep-regex",
    "grep-searcher",
    "ignore",
    "regex",
    "rayon",
]
syntect-printer = [
    "syntect",
    "rayon",
    "unicode-width",
    "bincode",
    "flate2",
    "rgb2ansi256",
    "term",
]
bat-printer = [
    "bat",
]

[dependencies]
anyhow = "1"
clap = { version = "3.0.0-beta", default-features = false, features = ["std", "color", "suggestions"] }
clap_generate = "3.0.0-beta"
console = "0.15"
memchr = "2"
ansi_term = "0.12"
pathdiff = "0.2"
bat = { version = "^0.18.3", default-features = false, features = ["regex-onig"], optional = true }
grep-regex = { version = "0.1.9", optional = true }
grep-searcher = { version = "0.1.8", optional = true }
ignore = { version = "0.4", optional = true }
regex = { version = "1", optional = true }
grep-matcher = { version = "0.1.5", optional = true }
grep-pcre2 = { version = "0.1.5", optional = true }
syntect = { version = "4.6", optional = true }
rayon = { version = "1", optional = true }
unicode-width = { version = "0.1.9", optional = true }
bincode = { version = "1.3", optional = true }
flate2 = { version = "1", optional = true }
rgb2ansi256 = { version = "0.1", optional = true }
term = { version = "0.7", optional = true }

[workspace]
members = [
    "hgrep-bench",
]
