[package]
name = "batgrep"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ripgrep"]
ripgrep = [
    "grep-regex",
    "grep-searcher",
    "rayon",
    "ignore",
    "regex",
]

[dependencies]
anyhow = "1"
bat = { version = "^0.18.3", default-features = false, features = ["regex-onig"] }
clap = { version = "3.0.0-beta", default-features = false, features = ["std", "color", "suggestions"] }
grep-regex = { version = "0.1.9", optional = true }
grep-searcher = { version = "0.1.8", optional = true }
rayon = { version = "1", optional = true }
ignore = { version = "0.4", optional = true }
regex = { version = "1", optional = true }
