name: CI
on: [push, pull_request]

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test --color always
      - name: Build and run
        run: cargo run --color always -- hgrep README.md
      - name: Build and run without builtin ripgrep
        run: cargo run --color always --no-default-features --features syntect-printer -- --version
      - name: Build and run with minimal features
        run: cargo run --color always --no-default-features -- --version
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: rustfmt
        run: cargo fmt -- --check --color always
      - name: clippy
        run: cargo clippy --color always -- -D warnings
