name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
  upload:
    name: Upload release binary
    strategy:
      fail-fast: false
      matrix:
        build: [linux, mac, win]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: mac
            os: macos-latest
            target: x86_64-apple-darwin
          - build: win
            os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - id: info
        # $GITHUB_REF will have a value like "refs/tags/0.3.1". Extract "0.3.1" from it
        run: |
          ver="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=version::${ver}"
          echo "::set-output name=asset_dir::hgrep-${ver}-${TARGET}"
          echo "::set-output name=zip::hgrep-${ver}-${TARGET}.zip"
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --color always --target=${{ matrix.target }} --verbose
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          RUST_BACKTRACE: 1
      - name: Archive files
        if: matrix.build == 'linux' || matrix.build == 'mac'
        run: |
          mkdir ${{ steps.info.outputs.asset_dir }}
          cp target/${{ matrix.target }}/release/hgrep LICENSE.txt README.md ${{ steps.info.outputs.asset_dir }}
          zip ${{ steps.info.outputs.zip }} -r ${{ steps.info.outputs.asset_dir }}
      - name: Archive files
        if: matrix.build == 'win'
        shell: bash
        run: |
          mkdir ${{ steps.info.outputs.asset_dir }}
          cp target/${{ matrix.target }}/release/hgrep.exe LICENSE.txt README.md ${{ steps.info.outputs.asset_dir }}
          7z a ${{ steps.info.outputs.zip }} ${{ steps.info.outputs.asset_dir }}
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.info.outputs.version }}
          draft: false
          prerelease: false
          files: ${{ steps.info.outputs.zip }}
